### ISSUE TITLE
Add KCT: Koin Crew Token

### ISSUE THREAD

**Issue by koincrew** [koindx/token-list#30]
**Please provide the following information for your token.**

Token Name: Koin Crew Token

Token Network: Koinos

Token Symbol: KCT

Token Description: Koin Crew Token in the official community coin crafted exclusively for the ardent supporters of Koin Crew. This token is not just a digital asset; it symbolizes the unwavering faith and commitment of the Koin Crew community.

Token Decimals: 8

Token Address: 1BTQCpospHJRA7VAtZ4wvitdcqYCvkwBCD

Has Allowances: Yes

Contract Repository: https://koincity.com/launchpad/1

Token Logo png: https://koincrew.com/IMG/kct-logo.png

Token/Project website: https://koincrew.com/

Token Coingecko ID:

Token Coinmarketcap ID

Token Audit: https://koincity.com/launchpad/1

**Comment by vonlooten** [comment]
@koincrew 

> Token Network: Koinos 

Is this a listing request for Harbinger and/or Mainnet?

**Comment by koincrew** [comment]
Yes, for Mainnet.

**Comment by vonlooten** [comment]
@koincrew 
I will try to figure out if we can list KCT token without having an open sourced contract.
