### ISSUE TITLE
PUNKSK: PunksKoin

### ISSUE THREAD

**Issue by KoinosPunks** [koindx/token-list#35]
Token Name: PunksKoin

Token Network: Mainnet and Harbinger

Token Symbol: PUNKSK

Token Description: PunksKoin is an innovative cryptocurrency that is allocated each month for the owners of the Koinos Punks and Koinos CyborgPunks NFT. Get your punk and get a steady supply of PunksKoin each month until all the crypto has been allocated to the NFT holders. PunksKoin has a fair launch with 0% for Founders, 0% Royalties, and 0% Fees and 100& allocated to the NFT holders.

Token Decimals: 8

Token Address: 1Q9o3uTa6L9XMFeUM5yfZyYuyGxn1ai2gx

Has Allowances: Yes

Contract Repository: hhttps://github.com/KoinosPunks/punks-koin-contract

Token Logo png: https://images2.imgbox.com/d8/61/FCe9B06h_o.png

Token/Project website: Not yet

Token Coingecko ID: Not yet

Token Coinmarketcap ID: Not yet

Token Audit: none

**Comment by vonlooten** [comment]
@KoinosPunks the provided image link does not work.

**Comment by KoinosPunks** [comment]
Hi,

We apologize, apparently the link expired. Here you can find a link that works: https://images2.imgbox.com/d8/61/FCe9B06h_o.png

**Comment by vonlooten** [comment]
@KoinosPunks your token contract url does not work. Maybe the repository is not public
