### ISSUE TITLE
Add UP: Liquidity

### ISSUE THREAD

**Issue by koincrew** [koindx/token-list#38]
**Please provide the following information for your token.**

Token Name: Liquidity

Token Network: Mainnet

Token Symbol: UP

Token Description: Liquidity (UP) Coin addresses the liquidity challenges on the Koinos Network while providing opportunities for users to make swaps with arbitrage.

Token Decimals: 8

Token Address: 17t977jJZ7DYKPQsjqtStbpvmde1DditXW

Has Allowances: yes

Contract Repository: https://koincity.com/launchpad/4

Token Logo png: https://tokens.koincrew.com/IMG/liquidity-logo.jpg

Token/Project website: ipfs://bafkreigauege5a6h63yoqmlwwpu4v45val2ffvbba74ffybmrekwlohrci/

Token Coingecko ID: not listed

Token Coinmarketcap ID: not listed

Token Audit: Koincity Audit

**Comment by Dokterkraakbeen** [comment]
Do you have a better resolution of the Liquidity logo? SVG is also good.

**Comment by cpad123** [comment]
![IMG_1253](https://github.com/koindx/token-list/assets/77091708/34c28261-862a-4291-9cb3-5033958b742e)

is this image any better?

**Comment by vonlooten** [comment]
@Dokterkraakbeen
