### ISSUE TITLE
Add {FR}: {Frenchie}

### ISSUE THREAD

**Issue by richardcrill** [koindx/token-list#42]
**Please provide the following information for your token.**

Token Name: Frenchie

Token Network:  MAINNET

Token Symbol: FR

Token Description: Meme koin of the beloved French Bulldog breed

Token Decimals: 8

Token Address: 1C4pGZS9oBBLs4vCTehGNBa7StXqYFRc16

Has Allowances: yes

Contract Repository: https://github.com/MiXiBo/Koincity-Standard-Token

Token Logo png: 
![frenchy](https://github.com/koindx/token-list/assets/27929603/60ccfb83-2cf7-4402-aa3a-20b5ebde9a1a)

Token/Project website: https://koincity.com/launchpad/9

Token Coingecko ID: none

Token Coinmarketcap ID none

Token Audit:  https://koincity.com/launchpad/9

**Comment by vonlooten** [comment]
@richardcrill the contract repository is probably https://github.com/MiXiBo/Koincity-Standard-Token

**Comment by vonlooten** [comment]
Hello @richardcrill  we have changed our listing approach: https://github.com/koindx/token-list/blob/main/README.md

**Comment by richardcrill** [comment]
Hi, I appreciate the message as I have been checking every day to see if
Frenchie has been listed. I see EGG got listed. Did they go through the new
listing approach? It seems unfair to me that I completed the process before
the approach changed, but now have to go through the new approach.
Obviously you don't have to be fair or even answer my questions, but I
wanted to let you know what I thought.

**Comment by vonlooten** [comment]
@richardcrill when you have submitted your issue you will probably have read the disclaimer in the Readme file:

> ## Disclaimer
> 
> Note filing an issue does not guarantee addition to this default token list. We do not review token addition requests in any particular order, and we do not guarantee that we will review your request to add the token to the default list.
> 

As has always been the case with our token list, we don't guarantee inclusion on the list and we don't consider requests in any particular order.

Please refrain from replying to this closed issue. Feel free to submit a listing application through our form. We have informed you and other projects which created and even have not created an issue directly to make sure everyone is aware about our new submission policy.
