### ISSUE TITLE
Add MARS: ElonKOIN

### ISSUE THREAD

**Issue by ElonKOIN** [koindx/token-list#44]
**Please provide the following information for your token.**

Token Name: ElonKOIN

Token Network: Koinos Mainnet

Token Symbol: MARS

Token Description: Elon Meme Koin created to raise awareness of Koinos Blockchain through social networks

Token Decimals: 8

Token Address: 189TkvhzpeRg56EnhysLa5YP9ufvaXTcWn

Has Allowances: yes

Contract Repository: https://koinosblocks.com/address/189TkvhzpeRg56EnhysLa5YP9ufvaXTcWn

Token Logo png: https://ibb.co/4t4wWcX

Token/Project website: n/a

Token Coingecko ID: n/a

Token Coinmarketcap ID: n/a

Token Audit: KoinCity

**Comment by ElonKOIN** [comment]
https://github.com/MiXiBo/Koincity-Standard-Token

**Comment by vonlooten** [comment]
Hello @ElonKOIN we have changed our listing approach: https://github.com/koindx/token-list/blob/main/README.md
