### ISSUE TITLE
Add MK: 1000

### ISSUE THREAD

**Issue by ElonKOIN** [koindx/token-list#48]
**Please provide the following information for your token.**

Token Name: 1000

Token Network: Koinos Mainnet

Token Symbol: MK

Token Description:  Mysteriously created, fair launched all 1000 tokens with 1 Koinos.  Community owned Meme coin

Token Decimals: 8

Token Address: 1HMmpaijocfMvTXDZ6hchQdqDfg2YoFdca

Has Allowances: Yes

Contract Repository:  https://koinosblocks.com/address/1HMmpaijocfMvTXDZ6hchQdqDfg2YoFdca

Token Logo png:  https://ibb.co/Sfx1Bff

Token/Project website:  n/a

Token Coingecko ID:  n/a

Token Coinmarketcap ID  n/a

Token Audit:  Koincity audit

**Comment by ElonKOIN** [comment]
https://github.com/MiXiBo/Koincity-Standard-Token

**Comment by vonlooten** [comment]
Hello @ElonKOIN we have changed our listing approach: https://github.com/koindx/token-list/blob/main/README.md
